[build]
cmd = "go build -o kodo ./main.go"
bin = "./kodo"
include_ext = ["go"]
exclude_dir = [
    "tmp",
    ".kodo",
    "web",
]

[build.color]
main = "blue"
watcher = "green"
build = "yellow"
runner = "magenta"
